version: '3.9'

services:
  php:
    image: reading-php-src:${TAG}
    container_name: reading-php-src
    volumes:
      - ./src:/usr/local/src/php-src/src
      - ./docker/php.ini:/usr/local/lib/php.ini
    tty: true
